spring.application.name=BW_CMR
spring.config.import=file:env.properties
server.port=3001
# Configuration dp
spring.datasource.url=${pg.url}
spring.datasource.password=${pg.password}
spring.datasource.username=${pg.username}
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=update
# Jwt Config
jwt.secret=${jwt.secret}
#Cloudinary
cloudinary.name=${cloudinary.name}
cloudinary.key=${cloudinary.key}
cloudinary.secret=${cloudinary.secret}

//DimensioneImg
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB